pipeline:
  identifier: Build_ecr_image_harness_1690901611358
  name: ECR Tutorial
  orgIdentifier: default
  projectIdentifier: ECR
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1690901528904
        repoName: Navratan135/ecr-image-harness
  stages:
    - stage:
        identifier: build
        name: Build and Test
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npmtest
                  name: Run Test
                  spec:
                    shell: Sh
                    command: |-
                      #echo "Welcome to Harness CI"
                      #npm install
                      #npm run build --if-present
                      npm run test
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushECR
                  name: Build And Push to ECR
                  identifier: Build_And_Push_to_ECR
                  spec:
                    connectorRef: AWS_Connector
                    region: ca-central-1
                    account: "880522693106"
                    imageName: ecr-image-harness
                    tags:
                      - testing
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
        type: CI
  tags: {}
